require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/expo/scripts/autolinking'
require 'json'

platform :ios, '13.0'

install! 'cocoapods',
  deterministic_uuids: false

target 'flappybird' do
  use_expo_modules!

  use_frameworks! linkage: :static

  use_react_native!(
    path: '../node_modules/react-native',
    hermes_enabled: false,
    fabric_enabled: false,
    app_path: File.expand_path('..', __dir__)
  )

  pod 'Google-Mobile-Ads-SDK'

  post_install do |installer|
    # ✅ Disable checksum validation for boost here ONLY (after install logic is initialized)
    installer.pods_project.targets.each do |target|
      if target.name.include?('boost')
        target.build_configurations.each do |config|
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
      end
    end

    react_native_post_install(installer)

    # ✅ Fix for resource bundle code signing
    installer.target_installation_results.pod_target_installation_results
      .each do |_, target_installation_result|
        target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
          resource_bundle_target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
  end
end
